### ISSUE TITLE
Import errors with tensorflow version 0.12.1

### ISSUE THREAD

**Issue by mads14** [devsisters/pointer-network-tensorflow#1]
Hi,
 
I just cloned your repo and downloaded tensorflow version 0.12.1. I am trying to run your example code. I am getting errors on the imports:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from trainer import Trainer
  File ".../pointer-network-tensorflow/trainer.py", line 7, in <module>
    from model import Model
  File ".../pointer-network-tensorflow/model.py", line 4, in <module>
    from layers import *
  File ".../pointer-network-tensorflow/layers.py", line 7, in <module>
    LSTMCell = rnn.LSTMCell
AttributeError: 'module' object has no attribute 'LSTMCell'.

From looking at the tensorflow docs it seems that LSTMCell is now located at:
tf.nn.rnn_cell.STMCell. I changed the code to read: LSTMCell = tf.nn.rnn_cell.LSTMCell and made a similar change for the next line of layers.py: MultiRNNCell = tf.nn.rnn_cell.MultiRNNCell.

I'm now getting a similar error on the seq2seq line, and can't figure out how to fix it:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from trainer import Trainer
  File ".../pointer-network-tensorflow/trainer.py", line 7, in <module>
    from model import Model
  File ".../pointer-network-tensorflow/model.py", line 4, in <module>
    from layers import *
  File ".../pointer-network-tensorflow/layers.py", line 9, in <module>
    dynamic_rnn_decoder = seq2seq.dynamic_rnn_decoder
AttributeError: 'module' object has no attribute 'dynamic_rnn_decoder'

It seems that tensorflow.contrib.seq2seq exists but does not have a dynamic_rnn_decoder function in version 12.1.0? Can you confirm that this is still working on your version and that you are in fact using tensorflow version 12.1.0. 

Thanks!
Maddie

**Comment by wangliangguo** [comment]
tf.nn.rnn_cell.LSTMCell

**Comment by fd3kyt** [comment]
It seems that `tf 0.12.1` doesn't have `dynamic_rnn_decoder` or `simple_decoder_fn_train`, I made it work on `tf 1.0.0`.

In `layers.py`:
replace 
```
LSTMCell = rnn.LSTMCell
MultiRNNCell = rnn.MultiRNNCell
dynamic_rnn_decoder = seq2seq.dynamic_rnn_decoder
simple_decoder_fn_train = seq2seq.simple_decoder_fn_train
```
to
```
LSTMCell = tf.contrib.rnn.LSTMCell
MultiRNNCell = tf.contrib.rnn.MultiRNNCell
dynamic_rnn_decoder = tf.contrib.seq2seq.dynamic_rnn_decoder
simple_decoder_fn_train = tf.contrib.seq2seq.simple_decoder_fn_train
```

In `model.py`: change all `tf.concat_v2` to `tf.concat`.

After that, it will still complain that `tf.contrib.layers` doesn't contain `utils`. I modified `site-packages/tensorflow/contrib/layers/__init__.py`, adding `'utils'` into `_allowed_symbols`, and it worked. Perhap there is a better way to do this.

**Comment by tuan3w** [comment]
I changed file model.py as [link](https://gist.github.com/tuan3w/943705773b07ff5be7b988292315136c), and it worked with tensorflow v1.0 without any modification in tensorflow library.

**Comment by unnir** [comment]
why did you close this issue? I still have the same problem
